[build]
  publish = "."
  
[functions]
  directory = "netlify/functions"
  included_files = ["docs/**/*", "system-prompt-encrypted.json"]
  
[functions.chat]
  timeout = 600

# Local development settings
[dev]
  functionsTimeout = 600

# Load environment variables for local development
[context.dev.environment]
  SYSTEM_PROMPT_KEY = "0190e991e45d7f8004f4655ed47d283fb2baf1feac6cc08787f85c90546f85d2"

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200