[build]
  publish = "."
  command = ""
  
[build.environment]
  NODE_ENV = "production"
  
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["docs/**/*", "system-prompt-encrypted.json"]

[functions."*"]
  timeout = "10m"

# Local development settings
[dev]
  functionsTimeout = "10m"
  framework = "#static"

# REMOVE THE HARDCODED KEY - Set via Netlify dashboard instead
[context.dev.environment]
  NODE_ENV = "development"

[context.production.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200